LOG:  database system was shut down at 2015-12-21 14:15:56 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  role "Paolo" does not exist
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-21 14:16:03 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-21 14:33:09 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  role "paronne" does not exist
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-21 14:59:43 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-21 15:01:55 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-21 15:18:24 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  duplicate key value violates unique constraint "orders_pkey"
DETAIL:  Key (orderid)=(1) already exists.
STATEMENT:  insert into orders (orderid, customerid, employeeid, orderdate, requireddate, shippeddate, shipvia, freight, shipname, shipaddress, shipcity, shipregion, shippostalcode, shipcountry) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-22 09:18:22 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-22 09:30:09 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-22 09:52:34 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-22 10:12:29 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-22 12:16:04 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-22 14:46:36 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  operator does not exist: character = integer at character 39
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  select * from orders where customerid = 10300;
ERROR:  operator does not exist: integer ~~ unknown at character 36
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  select * from orders where orderid like '10300';
ERROR:  operator does not exist: integer ~~ unknown at character 36
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
STATEMENT:  select * from orders where orderid like '10300';
ERROR:  function pg_catalog.substring(integer, integer, integer) does not exist at character 35
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  select orderid from orders  where substring(orderid, $1, $2) = $3 limit $4
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-22 19:25:54 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-23 16:27:36 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-24 09:37:21 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-24 11:11:09 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-24 11:41:13 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-24 14:58:26 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-24 18:31:06 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-25 16:05:40 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-27 23:28:13 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-28 10:28:21 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-28 12:37:50 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  duplicate key value violates unique constraint "orders_pkey"
DETAIL:  Key (orderid)=(1) already exists.
STATEMENT:  insert into orders (orderid, customerid, employeeid, orderdate, requireddate, shippeddate, shipvia, freight, shipname, shipaddress, shipcity, shipregion, shippostalcode, shipcountry) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ERROR:  duplicate key value violates unique constraint "orders_pkey"
DETAIL:  Key (orderid)=(2) already exists.
STATEMENT:  insert into orders (orderid, customerid, employeeid, orderdate, requireddate, shippeddate, shipvia, freight, shipname, shipaddress, shipcity, shipregion, shippostalcode, shipcountry) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ERROR:  duplicate key value violates unique constraint "orders_pkey"
DETAIL:  Key (orderid)=(3) already exists.
STATEMENT:  insert into orders (orderid, customerid, employeeid, orderdate, requireddate, shippeddate, shipvia, freight, shipname, shipaddress, shipcity, shipregion, shippostalcode, shipcountry) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-28 18:32:57 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-30 09:02:40 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-30 14:57:45 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-30 15:01:26 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-30 15:46:01 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-30 15:54:49 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-30 20:17:40 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2015-12-31 15:41:29 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-01 15:10:57 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-05 01:08:43 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-05 02:13:53 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-05 02:25:31 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-05 02:29:24 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-06 07:50:20 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-06 08:17:44 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-06 09:08:00 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-06 17:39:26 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-07 00:59:37 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-07 08:37:33 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-07 18:17:06 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-07 23:04:27 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-08 01:44:20 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-08 08:34:53 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  database "example" does not exist
FATAL:  database "bug_db" does not exist
FATAL:  database "log_data" does not exist
FATAL:  database "pdf_forms" does not exist
FATAL:  database "svy_framework" does not exist
FATAL:  database "tree" does not exist
FATAL:  database "user_data" does not exist
FATAL:  database "bug_db" does not exist
FATAL:  database "example" does not exist
FATAL:  database "log_data" does not exist
FATAL:  database "pdf_forms" does not exist
FATAL:  database "svy_framework" does not exist
FATAL:  database "tree" does not exist
FATAL:  database "user_data" does not exist
FATAL:  database "bug_db" does not exist
FATAL:  database "example" does not exist
FATAL:  database "log_data" does not exist
FATAL:  database "pdf_forms" does not exist
FATAL:  database "svy_framework" does not exist
FATAL:  database "tree" does not exist
FATAL:  database "user_data" does not exist
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-09 00:18:18 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-09 00:19:28 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-09 00:22:03 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-09 00:26:17 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-09 00:28:18 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-09 02:51:34 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-09 09:58:33 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-11 04:23:25 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-11 04:25:24 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  null value in column "categoryname" violates not-null constraint
DETAIL:  Failing row contains (13, null, null, null).
STATEMENT:  insert into categories (categoryid, categoryname, description, picture) values ($1, $2, $3, $4)
ERROR:  null value in column "categoryname" violates not-null constraint
DETAIL:  Failing row contains (14, null, null, null).
STATEMENT:  insert into categories (categoryid, categoryname, description, picture) values ($1, $2, $3, $4)
ERROR:  null value in column "categoryname" violates not-null constraint
DETAIL:  Failing row contains (26, null, null, null).
STATEMENT:  insert into categories (categoryid, categoryname, description, picture) values ($1, $2, $3, $4)
ERROR:  null value in column "categoryname" violates not-null constraint
DETAIL:  Failing row contains (40, null, null, null).
STATEMENT:  insert into categories (categoryid, categoryname, description, picture) values ($1, $2, $3, $4)
ERROR:  null value in column "categoryname" violates not-null constraint
DETAIL:  Failing row contains (42, null, null, null).
STATEMENT:  insert into categories (categoryid, categoryname, description, picture) values ($1, $2, $3, $4)
ERROR:  null value in column "categoryname" violates not-null constraint
DETAIL:  Failing row contains (47, null, null, null).
STATEMENT:  insert into categories (categoryid, categoryname, description, picture) values ($1, $2, $3, $4)
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: No error
HINT:  Is another postmaster already running on port 3023? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  database system was shut down at 2016-01-11 08:13:00 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-13 21:55:21 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-13 22:09:39 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-13 22:14:35 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-13 22:37:56 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-13 23:13:18 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 00:03:24 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 00:15:43 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 01:03:24 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 08:24:50 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 19:14:46 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 19:26:07 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 19:27:35 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 19:38:59 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 20:06:47 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-14 20:07:31 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-15 02:17:50 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-15 03:52:46 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-15 17:30:55 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-15 17:41:20 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-15 19:50:53 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-16 08:40:03 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-18 22:13:44 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-18 22:30:48 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-18 23:35:02 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 00:13:50 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 00:16:05 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 01:39:05 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 01:44:37 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(91ed2660-51c0-4c00-881f-1eb0192585a3) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f6d4c41f-9d22-437a-b8eb-3edfa5c23789) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(bb69059b-1cb4-4d57-9843-65162a2fc506) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(ff4edff7-572e-4ef0-b9f6-466a25d98cb1) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(FBC811CB-58BF-4B12-A439-DDAC2C4BAA80) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(7B656072-14BD-44D6-B83A-E0639E2E01F7) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(105fd97c-9871-4da0-b641-31b45e78c732) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(7B656072-14BD-44D6-B83A-E0639E2E01F7) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(e38efa49-1718-4fdc-be48-49ec45c42f09) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f8c874dd-5b12-4e08-9334-1e87786bc322) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f1e570ec-427e-4e88-8640-753c2088642d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(490ab122-3e6d-4155-b923-9321908ef2fa) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(959315c2-1af1-4e8e-b1dd-8b4a357aad4c) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(14b63fd4-ba40-41d2-a43a-21007e3b8f95) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(1db076f4-387d-4990-8b61-bfeec9542f1d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(959315c2-1af1-4e8e-b1dd-8b4a357aad4c) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(4699a2c2-5732-44c6-9129-c970d403b013) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(592B25F3-1E19-4DCC-A382-015A36B61E9E) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(4699a2c2-5732-44c6-9129-c970d403b013) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(490ab122-3e6d-4155-b923-9321908ef2fa) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f1e570ec-427e-4e88-8640-753c2088642d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(6b1dbd23-89c2-4225-85a0-46c38cf4cd14) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f8c874dd-5b12-4e08-9334-1e87786bc322) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(e38efa49-1718-4fdc-be48-49ec45c42f09) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(FBC811CB-58BF-4B12-A439-DDAC2C4BAA80) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c1b527cf-ad07-4ae5-a6c3-f14940eba8db) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(ff4edff7-572e-4ef0-b9f6-466a25d98cb1) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(97f2e287-8fa1-4b00-a9db-31f6adc37728) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(bb69059b-1cb4-4d57-9843-65162a2fc506) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(91ed2660-51c0-4c00-881f-1eb0192585a3) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f6d4c41f-9d22-437a-b8eb-3edfa5c23789) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(7B656072-14BD-44D6-B83A-E0639E2E01F7) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(105fd97c-9871-4da0-b641-31b45e78c732) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(14b63fd4-ba40-41d2-a43a-21007e3b8f95) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(959315c2-1af1-4e8e-b1dd-8b4a357aad4c) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(1db076f4-387d-4990-8b61-bfeec9542f1d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f1e570ec-427e-4e88-8640-753c2088642d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(490ab122-3e6d-4155-b923-9321908ef2fa) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(4699a2c2-5732-44c6-9129-c970d403b013) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(592B25F3-1E19-4DCC-A382-015A36B61E9E) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(FBC811CB-58BF-4B12-A439-DDAC2C4BAA80) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(e38efa49-1718-4fdc-be48-49ec45c42f09) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f8c874dd-5b12-4e08-9334-1e87786bc322) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(6b1dbd23-89c2-4225-85a0-46c38cf4cd14) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(ff4edff7-572e-4ef0-b9f6-466a25d98cb1) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c1b527cf-ad07-4ae5-a6c3-f14940eba8db) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(91ed2660-51c0-4c00-881f-1eb0192585a3) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(bb69059b-1cb4-4d57-9843-65162a2fc506) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(97f2e287-8fa1-4b00-a9db-31f6adc37728) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(ff4edff7-572e-4ef0-b9f6-466a25d98cb1) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c1b527cf-ad07-4ae5-a6c3-f14940eba8db) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(ff4edff7-572e-4ef0-b9f6-466a25d98cb1) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 02:52:38 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 02:54:05 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 03:07:51 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 03:24:46 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 09:16:58 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  null value in column "owner_id" violates not-null constraint
DETAIL:  Failing row contains (Servoy, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2016-01-19 09:32:57.749).
STATEMENT:  insert into sec_owner (name, owner_id, password_times_wrong, license_amount, database_name, hash, filter_field_organization, password_timespan_before_lock, password_input_interval, session_inactive_before_lock, allow_org_filter_change, company_name, deletion_date, modification_date, main_user_id, activation_date, registration_date, creation_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  null value in column "owner_id" violates not-null constraint
DETAIL:  Failing row contains (Servoy, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2016-01-19 09:33:40.461).
STATEMENT:  insert into sec_owner (name, owner_id, password_times_wrong, license_amount, database_name, hash, filter_field_organization, password_timespan_before_lock, password_input_interval, session_inactive_before_lock, allow_org_filter_change, company_name, deletion_date, modification_date, main_user_id, activation_date, registration_date, creation_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-19 18:34:52 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(91ed2660-51c0-4c00-881f-1eb0192585a3) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f6d4c41f-9d22-437a-b8eb-3edfa5c23789) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(bb69059b-1cb4-4d57-9843-65162a2fc506) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(ff4edff7-572e-4ef0-b9f6-466a25d98cb1) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(FBC811CB-58BF-4B12-A439-DDAC2C4BAA80) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(7B656072-14BD-44D6-B83A-E0639E2E01F7) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(105fd97c-9871-4da0-b641-31b45e78c732) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(7B656072-14BD-44D6-B83A-E0639E2E01F7) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(e38efa49-1718-4fdc-be48-49ec45c42f09) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f8c874dd-5b12-4e08-9334-1e87786bc322) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f1e570ec-427e-4e88-8640-753c2088642d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(490ab122-3e6d-4155-b923-9321908ef2fa) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(959315c2-1af1-4e8e-b1dd-8b4a357aad4c) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(14b63fd4-ba40-41d2-a43a-21007e3b8f95) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(1db076f4-387d-4990-8b61-bfeec9542f1d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(959315c2-1af1-4e8e-b1dd-8b4a357aad4c) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(4699a2c2-5732-44c6-9129-c970d403b013) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(592B25F3-1E19-4DCC-A382-015A36B61E9E) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(4699a2c2-5732-44c6-9129-c970d403b013) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(490ab122-3e6d-4155-b923-9321908ef2fa) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f1e570ec-427e-4e88-8640-753c2088642d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(6b1dbd23-89c2-4225-85a0-46c38cf4cd14) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f8c874dd-5b12-4e08-9334-1e87786bc322) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(e38efa49-1718-4fdc-be48-49ec45c42f09) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(FBC811CB-58BF-4B12-A439-DDAC2C4BAA80) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c1b527cf-ad07-4ae5-a6c3-f14940eba8db) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(ff4edff7-572e-4ef0-b9f6-466a25d98cb1) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(97f2e287-8fa1-4b00-a9db-31f6adc37728) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(bb69059b-1cb4-4d57-9843-65162a2fc506) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(91ed2660-51c0-4c00-881f-1eb0192585a3) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f6d4c41f-9d22-437a-b8eb-3edfa5c23789) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(7B656072-14BD-44D6-B83A-E0639E2E01F7) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(105fd97c-9871-4da0-b641-31b45e78c732) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(14b63fd4-ba40-41d2-a43a-21007e3b8f95) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(959315c2-1af1-4e8e-b1dd-8b4a357aad4c) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(1db076f4-387d-4990-8b61-bfeec9542f1d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f1e570ec-427e-4e88-8640-753c2088642d) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(490ab122-3e6d-4155-b923-9321908ef2fa) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(4699a2c2-5732-44c6-9129-c970d403b013) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(592B25F3-1E19-4DCC-A382-015A36B61E9E) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(FBC811CB-58BF-4B12-A439-DDAC2C4BAA80) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(e38efa49-1718-4fdc-be48-49ec45c42f09) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(f8c874dd-5b12-4e08-9334-1e87786bc322) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(6b1dbd23-89c2-4225-85a0-46c38cf4cd14) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(ff4edff7-572e-4ef0-b9f6-466a25d98cb1) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c1b527cf-ad07-4ae5-a6c3-f14940eba8db) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(91ed2660-51c0-4c00-881f-1eb0192585a3) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(bb69059b-1cb4-4d57-9843-65162a2fc506) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(97f2e287-8fa1-4b00-a9db-31f6adc37728) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(c02b9706-74bf-48b5-8394-f2dede4dbbb9) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(2F371EEF-5B76-4ACC-AACB-A30D02F73253) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(91ed2660-51c0-4c00-881f-1eb0192585a3) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(bb69059b-1cb4-4d57-9843-65162a2fc506) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(97f2e287-8fa1-4b00-a9db-31f6adc37728) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(bb69059b-1cb4-4d57-9843-65162a2fc506) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
ERROR:  duplicate key value violates unique constraint "svy_relations_pkey"
DETAIL:  Key (svy_relations_id)=(91ed2660-51c0-4c00-881f-1eb0192585a3) already exists.
STATEMENT:  insert into svy_relations (svy_relations_id, svy_tables_id_primary, svy_tables_id_foreign, relation_name, allow_creation, delete_related, allow_parent_delete, initial_sort, join_type, relation_items, i18n_key, include_in_search, include_in_export, one_to_one, is_foundset_self_join, display_name, modification_date, deletion_date) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-20 00:46:10 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-20 03:00:44 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-20 22:45:50 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-21 02:45:09 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  null value in column "customerid" violates not-null constraint
DETAIL:  Failing row contains (null, null, null, null, null, null, null, null, null, null, null, null).
STATEMENT:  insert into customers (customerid, companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax, organization_id) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ERROR:  null value in column "companyname" violates not-null constraint
DETAIL:  Failing row contains (TEST , null, null, null, null, null, null, null, null, null, null, null).
STATEMENT:  insert into customers (customerid, companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax, organization_id) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-21 18:15:47 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-21 22:33:53 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-22 04:55:52 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-22 18:57:49 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
FATAL:  terminating autovacuum process due to administrator command
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-22 18:58:34 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-25 11:39:38 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-25 13:25:35 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-25 16:11:55 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-25 16:53:16 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-25 19:42:46 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-26 10:39:10 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-26 13:26:55 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-26 15:49:05 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2016-01-26 15:49:54 CET
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  could not receive data from client: No connection could be made because the target machine actively refused it.
	
LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
